Base implementation of search engine
alsaderdinov/think-go pull request #1
Opened 2023-06-29 07:50 UTC by alsaderdinov

LGTM

2023-06-29 07:56 UTC, DmitriyVTitov requested changes
Думаю, что лучше переделать логику. Особенно про возврат ошибки.

2023-06-29 07:56 UTC, DmitriyVTitov commented on search/cmd/search/search.go
> +package main
Каждое ДЗ в отдельном каталоге.
https://github.com/thinknetica/go_course_4/blob/master/00-docs/Recommendations-and-rules.MD

2023-06-29 07:56 UTC, DmitriyVTitov commented on search/cmd/search/search.go
> +}
Эта функция не может вернуть ошибку в принципе.

2023-06-29 07:56 UTC, DmitriyVTitov commented on search/cmd/search/search.go
> +	}
Сканирование сайтов в Интернете непредсказуемо. Что тут считать ошибкой? Недоступность одного сайта? Всех вообще?
Не думаю, что это правильное поведение.

2023-06-29 09:34 UTC, alsaderdinov commented on search/cmd/search/search.go
> +}
убрал возврат ошибки из функции

2023-06-29 09:35 UTC, DmitriyVTitov commented on search/cmd/search/search.go
> +}
Я отписываюсь от всех репозиториев. :)

2023-06-29 09:37 UTC, alsaderdinov commented on search/cmd/search/search.go
> +}
пардон, не хотел вас пинговать ;(
просто ответил в комментарии, что замечания исправлены.

2023-06-29 09:38 UTC, alsaderdinov commented on search/cmd/search/search.go
> +	}
так как эта функция больше не возвращает ошибку, то убрал и обработку.

2023-07-01 07:39 UTC, DmitriyVTitov approved these changes
Всё хорошо.

2023-07-01 07:39 UTC, DmitriyVTitov commented on search/cmd/search/search.go
> +)
Я бы рекомендовал делать каталоги для каждого ДЗ типа: `hw-01`, `hw-02` ...

2023-07-01 10:30 UTC, merged